    server.port=8080
    banner.location=classpath:banner.txt
    logging.level.root=info
    management.endpoints.web.exposure.include=health
    management.endpoint.health.show-details=always
    spring.security.user.name=actuator
    spring.security.user.password=actuator
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://10.43.191.74:5432/gym?sslmode=disable&currentSchema=main_prod
    spring.datasource.username=user_prod
    spring.datasource.password=GYMNeotech02!02!
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
    app.security.enabled=false
    app.jwt.secret=my-secret-key
    shelly.device.status.url=https://shelly-267-eu.shelly.cloud/device/status
    shelly.relay.control.url=https://shelly-267-eu.shelly.cloud/v2/devices/api/set/switch
    shelly.id=901506811b54
    shelly.key=NDQ1YjVhdWlkC23C2CD387A7754006B5B8CC0D6575211E8D2642B08DA2B8AB5610C3FD63449FFD25B12C2108BE1F
    spring.task.scheduling.time-zone=Europe/Rome
    spring.mail.host=smtp.neotech.srl
    spring.mail.port=587
    spring.mail.username=gyminvestire@neotech.srl
    spring.mail.password=Neotech01!01
    spring.mail.from=gyminvestire@neotech.srl