package srl.neotech.ms_dipendenti.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccessoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public AccessoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIsNull() {
            addCriterion("\"utente_id\" is null");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIsNotNull() {
            addCriterion("\"utente_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andUtenteIdEqualTo(Integer value) {
            addCriterion("\"utente_id\" =", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotEqualTo(Integer value) {
            addCriterion("\"utente_id\" <>", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdGreaterThan(Integer value) {
            addCriterion("\"utente_id\" >", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"utente_id\" >=", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdLessThan(Integer value) {
            addCriterion("\"utente_id\" <", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"utente_id\" <=", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIn(List<Integer> values) {
            addCriterion("\"utente_id\" in", values, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotIn(List<Integer> values) {
            addCriterion("\"utente_id\" not in", values, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdBetween(Integer value1, Integer value2) {
            addCriterion("\"utente_id\" between", value1, value2, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"utente_id\" not between", value1, value2, "utenteId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdIsNull() {
            addCriterion("\"prenotazione_id\" is null");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdIsNotNull() {
            addCriterion("\"prenotazione_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdEqualTo(Integer value) {
            addCriterion("\"prenotazione_id\" =", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdNotEqualTo(Integer value) {
            addCriterion("\"prenotazione_id\" <>", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdGreaterThan(Integer value) {
            addCriterion("\"prenotazione_id\" >", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"prenotazione_id\" >=", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdLessThan(Integer value) {
            addCriterion("\"prenotazione_id\" <", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"prenotazione_id\" <=", value, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdIn(List<Integer> values) {
            addCriterion("\"prenotazione_id\" in", values, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdNotIn(List<Integer> values) {
            addCriterion("\"prenotazione_id\" not in", values, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdBetween(Integer value1, Integer value2) {
            addCriterion("\"prenotazione_id\" between", value1, value2, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andPrenotazioneIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"prenotazione_id\" not between", value1, value2, "prenotazioneId");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoIsNull() {
            addCriterion("\"data_ora_accesso\" is null");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoIsNotNull() {
            addCriterion("\"data_ora_accesso\" is not null");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoEqualTo(Date value) {
            addCriterion("\"data_ora_accesso\" =", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoNotEqualTo(Date value) {
            addCriterion("\"data_ora_accesso\" <>", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoGreaterThan(Date value) {
            addCriterion("\"data_ora_accesso\" >", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"data_ora_accesso\" >=", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoLessThan(Date value) {
            addCriterion("\"data_ora_accesso\" <", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoLessThanOrEqualTo(Date value) {
            addCriterion("\"data_ora_accesso\" <=", value, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoIn(List<Date> values) {
            addCriterion("\"data_ora_accesso\" in", values, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoNotIn(List<Date> values) {
            addCriterion("\"data_ora_accesso\" not in", values, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoBetween(Date value1, Date value2) {
            addCriterion("\"data_ora_accesso\" between", value1, value2, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andDataOraAccessoNotBetween(Date value1, Date value2) {
            addCriterion("\"data_ora_accesso\" not between", value1, value2, "dataOraAccesso");
            return (Criteria) this;
        }

        public Criteria andEsitoIsNull() {
            addCriterion("\"esito\" is null");
            return (Criteria) this;
        }

        public Criteria andEsitoIsNotNull() {
            addCriterion("\"esito\" is not null");
            return (Criteria) this;
        }

        public Criteria andEsitoEqualTo(String value) {
            addCriterion("\"esito\" =", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoNotEqualTo(String value) {
            addCriterion("\"esito\" <>", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoGreaterThan(String value) {
            addCriterion("\"esito\" >", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoGreaterThanOrEqualTo(String value) {
            addCriterion("\"esito\" >=", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoLessThan(String value) {
            addCriterion("\"esito\" <", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoLessThanOrEqualTo(String value) {
            addCriterion("\"esito\" <=", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoLike(String value) {
            addCriterion("\"esito\" like", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoNotLike(String value) {
            addCriterion("\"esito\" not like", value, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoIn(List<String> values) {
            addCriterion("\"esito\" in", values, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoNotIn(List<String> values) {
            addCriterion("\"esito\" not in", values, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoBetween(String value1, String value2) {
            addCriterion("\"esito\" between", value1, value2, "esito");
            return (Criteria) this;
        }

        public Criteria andEsitoNotBetween(String value1, String value2) {
            addCriterion("\"esito\" not between", value1, value2, "esito");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 17 08:54:50 CET 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}