package srl.neotech.ms_dipendenti.dto;

public class Configurazione {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_CONFIGURAZIONI.chiave
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    private String chiave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_CONFIGURAZIONI.valore
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    private String valore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_CONFIGURAZIONI.chiave
     *
     * @return the value of public.T_CONFIGURAZIONI.chiave
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public String getChiave() {
        return chiave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_CONFIGURAZIONI.chiave
     *
     * @param chiave the value for public.T_CONFIGURAZIONI.chiave
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void setChiave(String chiave) {
        this.chiave = chiave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_CONFIGURAZIONI.valore
     *
     * @return the value of public.T_CONFIGURAZIONI.valore
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public String getValore() {
        return valore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_CONFIGURAZIONI.valore
     *
     * @param valore the value for public.T_CONFIGURAZIONI.valore
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void setValore(String valore) {
        this.valore = valore;
    }
}