package srl.neotech.ms_dipendenti.dto;

import java.util.ArrayList;
import java.util.List;

public class ConfigurazioneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public ConfigurazioneExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChiaveIsNull() {
            addCriterion("\"chiave\" is null");
            return (Criteria) this;
        }

        public Criteria andChiaveIsNotNull() {
            addCriterion("\"chiave\" is not null");
            return (Criteria) this;
        }

        public Criteria andChiaveEqualTo(String value) {
            addCriterion("\"chiave\" =", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveNotEqualTo(String value) {
            addCriterion("\"chiave\" <>", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveGreaterThan(String value) {
            addCriterion("\"chiave\" >", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveGreaterThanOrEqualTo(String value) {
            addCriterion("\"chiave\" >=", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveLessThan(String value) {
            addCriterion("\"chiave\" <", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveLessThanOrEqualTo(String value) {
            addCriterion("\"chiave\" <=", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveLike(String value) {
            addCriterion("\"chiave\" like", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveNotLike(String value) {
            addCriterion("\"chiave\" not like", value, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveIn(List<String> values) {
            addCriterion("\"chiave\" in", values, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveNotIn(List<String> values) {
            addCriterion("\"chiave\" not in", values, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveBetween(String value1, String value2) {
            addCriterion("\"chiave\" between", value1, value2, "chiave");
            return (Criteria) this;
        }

        public Criteria andChiaveNotBetween(String value1, String value2) {
            addCriterion("\"chiave\" not between", value1, value2, "chiave");
            return (Criteria) this;
        }

        public Criteria andValoreIsNull() {
            addCriterion("\"valore\" is null");
            return (Criteria) this;
        }

        public Criteria andValoreIsNotNull() {
            addCriterion("\"valore\" is not null");
            return (Criteria) this;
        }

        public Criteria andValoreEqualTo(String value) {
            addCriterion("\"valore\" =", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotEqualTo(String value) {
            addCriterion("\"valore\" <>", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreGreaterThan(String value) {
            addCriterion("\"valore\" >", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreGreaterThanOrEqualTo(String value) {
            addCriterion("\"valore\" >=", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreLessThan(String value) {
            addCriterion("\"valore\" <", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreLessThanOrEqualTo(String value) {
            addCriterion("\"valore\" <=", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreLike(String value) {
            addCriterion("\"valore\" like", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotLike(String value) {
            addCriterion("\"valore\" not like", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreIn(List<String> values) {
            addCriterion("\"valore\" in", values, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotIn(List<String> values) {
            addCriterion("\"valore\" not in", values, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreBetween(String value1, String value2) {
            addCriterion("\"valore\" between", value1, value2, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotBetween(String value1, String value2) {
            addCriterion("\"valore\" not between", value1, value2, "valore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 02 16:43:28 CET 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}