package srl.neotech.ms_dipendenti.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PrenotazioneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public PrenotazioneExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIsNull() {
            addCriterion("\"utente_id\" is null");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIsNotNull() {
            addCriterion("\"utente_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andUtenteIdEqualTo(Integer value) {
            addCriterion("\"utente_id\" =", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotEqualTo(Integer value) {
            addCriterion("\"utente_id\" <>", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdGreaterThan(Integer value) {
            addCriterion("\"utente_id\" >", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"utente_id\" >=", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdLessThan(Integer value) {
            addCriterion("\"utente_id\" <", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"utente_id\" <=", value, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdIn(List<Integer> values) {
            addCriterion("\"utente_id\" in", values, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotIn(List<Integer> values) {
            addCriterion("\"utente_id\" not in", values, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdBetween(Integer value1, Integer value2) {
            addCriterion("\"utente_id\" between", value1, value2, "utenteId");
            return (Criteria) this;
        }

        public Criteria andUtenteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"utente_id\" not between", value1, value2, "utenteId");
            return (Criteria) this;
        }

        public Criteria andDataIsNull() {
            addCriterion("\"data\" is null");
            return (Criteria) this;
        }

        public Criteria andDataIsNotNull() {
            addCriterion("\"data\" is not null");
            return (Criteria) this;
        }

        public Criteria andDataEqualTo(Date value) {
            addCriterionForJDBCDate("\"data\" =", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"data\" <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThan(Date value) {
            addCriterionForJDBCDate("\"data\" >", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"data\" >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThan(Date value) {
            addCriterionForJDBCDate("\"data\" <", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"data\" <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andDataIn(List<Date> values) {
            addCriterionForJDBCDate("\"data\" in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"data\" not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andDataBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"data\" between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andDataNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"data\" not between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andOraInizioIsNull() {
            addCriterion("\"ora_inizio\" is null");
            return (Criteria) this;
        }

        public Criteria andOraInizioIsNotNull() {
            addCriterion("\"ora_inizio\" is not null");
            return (Criteria) this;
        }

        public Criteria andOraInizioEqualTo(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" =", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioNotEqualTo(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" <>", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioGreaterThan(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" >", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" >=", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioLessThan(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" <", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"ora_inizio\" <=", value, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioIn(List<Date> values) {
            addCriterionForJDBCTime("\"ora_inizio\" in", values, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioNotIn(List<Date> values) {
            addCriterionForJDBCTime("\"ora_inizio\" not in", values, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"ora_inizio\" between", value1, value2, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andOraInizioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"ora_inizio\" not between", value1, value2, "oraInizio");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiIsNull() {
            addCriterion("\"durata_minuti\" is null");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiIsNotNull() {
            addCriterion("\"durata_minuti\" is not null");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiEqualTo(Integer value) {
            addCriterion("\"durata_minuti\" =", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiNotEqualTo(Integer value) {
            addCriterion("\"durata_minuti\" <>", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiGreaterThan(Integer value) {
            addCriterion("\"durata_minuti\" >", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"durata_minuti\" >=", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiLessThan(Integer value) {
            addCriterion("\"durata_minuti\" <", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiLessThanOrEqualTo(Integer value) {
            addCriterion("\"durata_minuti\" <=", value, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiIn(List<Integer> values) {
            addCriterion("\"durata_minuti\" in", values, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiNotIn(List<Integer> values) {
            addCriterion("\"durata_minuti\" not in", values, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiBetween(Integer value1, Integer value2) {
            addCriterion("\"durata_minuti\" between", value1, value2, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andDurataMinutiNotBetween(Integer value1, Integer value2) {
            addCriterion("\"durata_minuti\" not between", value1, value2, "durataMinuti");
            return (Criteria) this;
        }

        public Criteria andStatoIsNull() {
            addCriterion("\"stato\" is null");
            return (Criteria) this;
        }

        public Criteria andStatoIsNotNull() {
            addCriterion("\"stato\" is not null");
            return (Criteria) this;
        }

        public Criteria andStatoEqualTo(String value) {
            addCriterion("\"stato\" =", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotEqualTo(String value) {
            addCriterion("\"stato\" <>", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoGreaterThan(String value) {
            addCriterion("\"stato\" >", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoGreaterThanOrEqualTo(String value) {
            addCriterion("\"stato\" >=", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLessThan(String value) {
            addCriterion("\"stato\" <", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLessThanOrEqualTo(String value) {
            addCriterion("\"stato\" <=", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLike(String value) {
            addCriterion("\"stato\" like", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotLike(String value) {
            addCriterion("\"stato\" not like", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoIn(List<String> values) {
            addCriterion("\"stato\" in", values, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotIn(List<String> values) {
            addCriterion("\"stato\" not in", values, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoBetween(String value1, String value2) {
            addCriterion("\"stato\" between", value1, value2, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotBetween(String value1, String value2) {
            addCriterion("\"stato\" not between", value1, value2, "stato");
            return (Criteria) this;
        }

        public Criteria andUsataIsNull() {
            addCriterion("\"usata\" is null");
            return (Criteria) this;
        }

        public Criteria andUsataIsNotNull() {
            addCriterion("\"usata\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsataEqualTo(Boolean value) {
            addCriterion("\"usata\" =", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataNotEqualTo(Boolean value) {
            addCriterion("\"usata\" <>", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataGreaterThan(Boolean value) {
            addCriterion("\"usata\" >", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataGreaterThanOrEqualTo(Boolean value) {
            addCriterion("\"usata\" >=", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataLessThan(Boolean value) {
            addCriterion("\"usata\" <", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataLessThanOrEqualTo(Boolean value) {
            addCriterion("\"usata\" <=", value, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataIn(List<Boolean> values) {
            addCriterion("\"usata\" in", values, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataNotIn(List<Boolean> values) {
            addCriterion("\"usata\" not in", values, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataBetween(Boolean value1, Boolean value2) {
            addCriterion("\"usata\" between", value1, value2, "usata");
            return (Criteria) this;
        }

        public Criteria andUsataNotBetween(Boolean value1, Boolean value2) {
            addCriterion("\"usata\" not between", value1, value2, "usata");
            return (Criteria) this;
        }

        public Criteria andCreataIsNull() {
            addCriterion("\"creata\" is null");
            return (Criteria) this;
        }

        public Criteria andCreataIsNotNull() {
            addCriterion("\"creata\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreataEqualTo(Date value) {
            addCriterion("\"creata\" =", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataNotEqualTo(Date value) {
            addCriterion("\"creata\" <>", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataGreaterThan(Date value) {
            addCriterion("\"creata\" >", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataGreaterThanOrEqualTo(Date value) {
            addCriterion("\"creata\" >=", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataLessThan(Date value) {
            addCriterion("\"creata\" <", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataLessThanOrEqualTo(Date value) {
            addCriterion("\"creata\" <=", value, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataIn(List<Date> values) {
            addCriterion("\"creata\" in", values, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataNotIn(List<Date> values) {
            addCriterion("\"creata\" not in", values, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataBetween(Date value1, Date value2) {
            addCriterion("\"creata\" between", value1, value2, "creata");
            return (Criteria) this;
        }

        public Criteria andCreataNotBetween(Date value1, Date value2) {
            addCriterion("\"creata\" not between", value1, value2, "creata");
            return (Criteria) this;
        }

        public Criteria andAnnullataIsNull() {
            addCriterion("\"annullata\" is null");
            return (Criteria) this;
        }

        public Criteria andAnnullataIsNotNull() {
            addCriterion("\"annullata\" is not null");
            return (Criteria) this;
        }

        public Criteria andAnnullataEqualTo(Date value) {
            addCriterion("\"annullata\" =", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataNotEqualTo(Date value) {
            addCriterion("\"annullata\" <>", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataGreaterThan(Date value) {
            addCriterion("\"annullata\" >", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataGreaterThanOrEqualTo(Date value) {
            addCriterion("\"annullata\" >=", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataLessThan(Date value) {
            addCriterion("\"annullata\" <", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataLessThanOrEqualTo(Date value) {
            addCriterion("\"annullata\" <=", value, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataIn(List<Date> values) {
            addCriterion("\"annullata\" in", values, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataNotIn(List<Date> values) {
            addCriterion("\"annullata\" not in", values, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataBetween(Date value1, Date value2) {
            addCriterion("\"annullata\" between", value1, value2, "annullata");
            return (Criteria) this;
        }

        public Criteria andAnnullataNotBetween(Date value1, Date value2) {
            addCriterion("\"annullata\" not between", value1, value2, "annullata");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 23 15:35:12 CET 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}