package srl.neotech.ms_dipendenti.dto;

import java.util.Date;

public class Prenotazione {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.utente_id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Integer utenteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.data
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Date data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.ora_inizio
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Date oraInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.durata_minuti
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Integer durataMinuti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.stato
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private String stato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.usata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Boolean usata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.creata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Date creata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_PRENOTAZIONI.annullata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    private Date annullata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.id
     *
     * @return the value of public.T_PRENOTAZIONI.id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.id
     *
     * @param id the value for public.T_PRENOTAZIONI.id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.utente_id
     *
     * @return the value of public.T_PRENOTAZIONI.utente_id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Integer getUtenteId() {
        return utenteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.utente_id
     *
     * @param utenteId the value for public.T_PRENOTAZIONI.utente_id
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setUtenteId(Integer utenteId) {
        this.utenteId = utenteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.data
     *
     * @return the value of public.T_PRENOTAZIONI.data
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.data
     *
     * @param data the value for public.T_PRENOTAZIONI.data
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.ora_inizio
     *
     * @return the value of public.T_PRENOTAZIONI.ora_inizio
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Date getOraInizio() {
        return oraInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.ora_inizio
     *
     * @param oraInizio the value for public.T_PRENOTAZIONI.ora_inizio
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setOraInizio(Date oraInizio) {
        this.oraInizio = oraInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.durata_minuti
     *
     * @return the value of public.T_PRENOTAZIONI.durata_minuti
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Integer getDurataMinuti() {
        return durataMinuti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.durata_minuti
     *
     * @param durataMinuti the value for public.T_PRENOTAZIONI.durata_minuti
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setDurataMinuti(Integer durataMinuti) {
        this.durataMinuti = durataMinuti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.stato
     *
     * @return the value of public.T_PRENOTAZIONI.stato
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public String getStato() {
        return stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.stato
     *
     * @param stato the value for public.T_PRENOTAZIONI.stato
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setStato(String stato) {
        this.stato = stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.usata
     *
     * @return the value of public.T_PRENOTAZIONI.usata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Boolean getUsata() {
        return usata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.usata
     *
     * @param usata the value for public.T_PRENOTAZIONI.usata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setUsata(Boolean usata) {
        this.usata = usata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.creata
     *
     * @return the value of public.T_PRENOTAZIONI.creata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Date getCreata() {
        return creata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.creata
     *
     * @param creata the value for public.T_PRENOTAZIONI.creata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setCreata(Date creata) {
        this.creata = creata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_PRENOTAZIONI.annullata
     *
     * @return the value of public.T_PRENOTAZIONI.annullata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public Date getAnnullata() {
        return annullata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_PRENOTAZIONI.annullata
     *
     * @param annullata the value for public.T_PRENOTAZIONI.annullata
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    public void setAnnullata(Date annullata) {
        this.annullata = annullata;
    }
}