package srl.neotech.ms_dipendenti.dto;

import java.util.Date;

public class Societa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_SOCIETA.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_SOCIETA.nome
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    private String nome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_SOCIETA.creata
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    private Date creata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_SOCIETA.id
     *
     * @return the value of public.T_SOCIETA.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_SOCIETA.id
     *
     * @param id the value for public.T_SOCIETA.id
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_SOCIETA.nome
     *
     * @return the value of public.T_SOCIETA.nome
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_SOCIETA.nome
     *
     * @param nome the value for public.T_SOCIETA.nome
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_SOCIETA.creata
     *
     * @return the value of public.T_SOCIETA.creata
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public Date getCreata() {
        return creata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_SOCIETA.creata
     *
     * @param creata the value for public.T_SOCIETA.creata
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    public void setCreata(Date creata) {
        this.creata = creata;
    }
}