package srl.neotech.ms_dipendenti.dto;

import java.util.Date;

public class Utente {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.nome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String nome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.cognome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String cognome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.email
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.telefono
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.data_nascita
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Date dataNascita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.sesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String sesso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.matricola
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String matricola;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.societa_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Integer societaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.stato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String stato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.creato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Date creato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.aggiornato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Date aggiornato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_UTENTI.tipo_utente
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String tipoUtente;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.id
     *
     * @return the value of public.T_UTENTI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.id
     *
     * @param id the value for public.T_UTENTI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.nome
     *
     * @return the value of public.T_UTENTI.nome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.nome
     *
     * @param nome the value for public.T_UTENTI.nome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.cognome
     *
     * @return the value of public.T_UTENTI.cognome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.cognome
     *
     * @param cognome the value for public.T_UTENTI.cognome
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.email
     *
     * @return the value of public.T_UTENTI.email
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.email
     *
     * @param email the value for public.T_UTENTI.email
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.telefono
     *
     * @return the value of public.T_UTENTI.telefono
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.telefono
     *
     * @param telefono the value for public.T_UTENTI.telefono
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.data_nascita
     *
     * @return the value of public.T_UTENTI.data_nascita
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Date getDataNascita() {
        return dataNascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.data_nascita
     *
     * @param dataNascita the value for public.T_UTENTI.data_nascita
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.sesso
     *
     * @return the value of public.T_UTENTI.sesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.sesso
     *
     * @param sesso the value for public.T_UTENTI.sesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.matricola
     *
     * @return the value of public.T_UTENTI.matricola
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getMatricola() {
        return matricola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.matricola
     *
     * @param matricola the value for public.T_UTENTI.matricola
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setMatricola(String matricola) {
        this.matricola = matricola;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.societa_id
     *
     * @return the value of public.T_UTENTI.societa_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Integer getSocietaId() {
        return societaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.societa_id
     *
     * @param societaId the value for public.T_UTENTI.societa_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setSocietaId(Integer societaId) {
        this.societaId = societaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.stato
     *
     * @return the value of public.T_UTENTI.stato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getStato() {
        return stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.stato
     *
     * @param stato the value for public.T_UTENTI.stato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setStato(String stato) {
        this.stato = stato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.creato
     *
     * @return the value of public.T_UTENTI.creato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Date getCreato() {
        return creato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.creato
     *
     * @param creato the value for public.T_UTENTI.creato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setCreato(Date creato) {
        this.creato = creato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.aggiornato
     *
     * @return the value of public.T_UTENTI.aggiornato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Date getAggiornato() {
        return aggiornato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.aggiornato
     *
     * @param aggiornato the value for public.T_UTENTI.aggiornato
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setAggiornato(Date aggiornato) {
        this.aggiornato = aggiornato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_UTENTI.tipo_utente
     *
     * @return the value of public.T_UTENTI.tipo_utente
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getTipoUtente() {
        return tipoUtente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_UTENTI.tipo_utente
     *
     * @param tipoUtente the value for public.T_UTENTI.tipo_utente
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setTipoUtente(String tipoUtente) {
        this.tipoUtente = tipoUtente;
    }
}