package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Accesso;
import srl.neotech.ms_dipendenti.dto.AccessoExample;

public interface AccessoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    long countByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int deleteByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int insert(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int insertSelective(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    List<Accesso> selectByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    Accesso selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByExampleSelective(@Param("row") Accesso row, @Param("example") AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByExample(@Param("row") Accesso row, @Param("example") AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByPrimaryKeySelective(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByPrimaryKey(Accesso row);
}