package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Utente;
import srl.neotech.ms_dipendenti.dto.UtenteExample;

public interface UtenteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    long countByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int deleteByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int insert(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int insertSelective(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    List<Utente> selectByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    Utente selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByExampleSelective(@Param("row") Utente row, @Param("example") UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByExample(@Param("row") Utente row, @Param("example") UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByPrimaryKeySelective(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    int updateByPrimaryKey(Utente row);
}