package srl.neotech.ms_dipendenti.dto;

import java.util.Date;

public class Accesso {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_ACCESSI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_ACCESSI.utente_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Integer utenteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_ACCESSI.prenotazione_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Integer prenotazioneId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_ACCESSI.data_ora_accesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private Date dataOraAccesso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.T_ACCESSI.esito
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    private String esito;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_ACCESSI.id
     *
     * @return the value of public.T_ACCESSI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_ACCESSI.id
     *
     * @param id the value for public.T_ACCESSI.id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_ACCESSI.utente_id
     *
     * @return the value of public.T_ACCESSI.utente_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Integer getUtenteId() {
        return utenteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_ACCESSI.utente_id
     *
     * @param utenteId the value for public.T_ACCESSI.utente_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setUtenteId(Integer utenteId) {
        this.utenteId = utenteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_ACCESSI.prenotazione_id
     *
     * @return the value of public.T_ACCESSI.prenotazione_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Integer getPrenotazioneId() {
        return prenotazioneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_ACCESSI.prenotazione_id
     *
     * @param prenotazioneId the value for public.T_ACCESSI.prenotazione_id
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setPrenotazioneId(Integer prenotazioneId) {
        this.prenotazioneId = prenotazioneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_ACCESSI.data_ora_accesso
     *
     * @return the value of public.T_ACCESSI.data_ora_accesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Date getDataOraAccesso() {
        return dataOraAccesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_ACCESSI.data_ora_accesso
     *
     * @param dataOraAccesso the value for public.T_ACCESSI.data_ora_accesso
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setDataOraAccesso(Date dataOraAccesso) {
        this.dataOraAccesso = dataOraAccesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.T_ACCESSI.esito
     *
     * @return the value of public.T_ACCESSI.esito
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getEsito() {
        return esito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.T_ACCESSI.esito
     *
     * @param esito the value for public.T_ACCESSI.esito
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setEsito(String esito) {
        this.esito = esito;
    }
}