package srl.neotech.ms_dipendenti.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UtenteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public UtenteExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNomeIsNull() {
            addCriterion("\"nome\" is null");
            return (Criteria) this;
        }

        public Criteria andNomeIsNotNull() {
            addCriterion("\"nome\" is not null");
            return (Criteria) this;
        }

        public Criteria andNomeEqualTo(String value) {
            addCriterion("\"nome\" =", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotEqualTo(String value) {
            addCriterion("\"nome\" <>", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThan(String value) {
            addCriterion("\"nome\" >", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeGreaterThanOrEqualTo(String value) {
            addCriterion("\"nome\" >=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThan(String value) {
            addCriterion("\"nome\" <", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLessThanOrEqualTo(String value) {
            addCriterion("\"nome\" <=", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeLike(String value) {
            addCriterion("\"nome\" like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotLike(String value) {
            addCriterion("\"nome\" not like", value, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeIn(List<String> values) {
            addCriterion("\"nome\" in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotIn(List<String> values) {
            addCriterion("\"nome\" not in", values, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeBetween(String value1, String value2) {
            addCriterion("\"nome\" between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andNomeNotBetween(String value1, String value2) {
            addCriterion("\"nome\" not between", value1, value2, "nome");
            return (Criteria) this;
        }

        public Criteria andCognomeIsNull() {
            addCriterion("\"cognome\" is null");
            return (Criteria) this;
        }

        public Criteria andCognomeIsNotNull() {
            addCriterion("\"cognome\" is not null");
            return (Criteria) this;
        }

        public Criteria andCognomeEqualTo(String value) {
            addCriterion("\"cognome\" =", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeNotEqualTo(String value) {
            addCriterion("\"cognome\" <>", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeGreaterThan(String value) {
            addCriterion("\"cognome\" >", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeGreaterThanOrEqualTo(String value) {
            addCriterion("\"cognome\" >=", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeLessThan(String value) {
            addCriterion("\"cognome\" <", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeLessThanOrEqualTo(String value) {
            addCriterion("\"cognome\" <=", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeLike(String value) {
            addCriterion("\"cognome\" like", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeNotLike(String value) {
            addCriterion("\"cognome\" not like", value, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeIn(List<String> values) {
            addCriterion("\"cognome\" in", values, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeNotIn(List<String> values) {
            addCriterion("\"cognome\" not in", values, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeBetween(String value1, String value2) {
            addCriterion("\"cognome\" between", value1, value2, "cognome");
            return (Criteria) this;
        }

        public Criteria andCognomeNotBetween(String value1, String value2) {
            addCriterion("\"cognome\" not between", value1, value2, "cognome");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("\"email\" is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("\"email\" is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("\"email\" =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("\"email\" <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("\"email\" >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("\"email\" >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("\"email\" <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("\"email\" <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("\"email\" like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("\"email\" not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("\"email\" in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("\"email\" not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("\"email\" between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("\"email\" not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("\"telefono\" is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("\"telefono\" is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("\"telefono\" =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("\"telefono\" <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("\"telefono\" >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("\"telefono\" >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("\"telefono\" <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("\"telefono\" <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("\"telefono\" like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("\"telefono\" not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("\"telefono\" in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("\"telefono\" not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("\"telefono\" between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("\"telefono\" not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andDataNascitaIsNull() {
            addCriterion("\"data_nascita\" is null");
            return (Criteria) this;
        }

        public Criteria andDataNascitaIsNotNull() {
            addCriterion("\"data_nascita\" is not null");
            return (Criteria) this;
        }

        public Criteria andDataNascitaEqualTo(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" =", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" <>", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaGreaterThan(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" >", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" >=", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaLessThan(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" <", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"data_nascita\" <=", value, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaIn(List<Date> values) {
            addCriterionForJDBCDate("\"data_nascita\" in", values, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"data_nascita\" not in", values, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"data_nascita\" between", value1, value2, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andDataNascitaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"data_nascita\" not between", value1, value2, "dataNascita");
            return (Criteria) this;
        }

        public Criteria andSessoIsNull() {
            addCriterion("\"sesso\" is null");
            return (Criteria) this;
        }

        public Criteria andSessoIsNotNull() {
            addCriterion("\"sesso\" is not null");
            return (Criteria) this;
        }

        public Criteria andSessoEqualTo(String value) {
            addCriterion("\"sesso\" =", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoNotEqualTo(String value) {
            addCriterion("\"sesso\" <>", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoGreaterThan(String value) {
            addCriterion("\"sesso\" >", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoGreaterThanOrEqualTo(String value) {
            addCriterion("\"sesso\" >=", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoLessThan(String value) {
            addCriterion("\"sesso\" <", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoLessThanOrEqualTo(String value) {
            addCriterion("\"sesso\" <=", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoLike(String value) {
            addCriterion("\"sesso\" like", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoNotLike(String value) {
            addCriterion("\"sesso\" not like", value, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoIn(List<String> values) {
            addCriterion("\"sesso\" in", values, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoNotIn(List<String> values) {
            addCriterion("\"sesso\" not in", values, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoBetween(String value1, String value2) {
            addCriterion("\"sesso\" between", value1, value2, "sesso");
            return (Criteria) this;
        }

        public Criteria andSessoNotBetween(String value1, String value2) {
            addCriterion("\"sesso\" not between", value1, value2, "sesso");
            return (Criteria) this;
        }

        public Criteria andMatricolaIsNull() {
            addCriterion("\"matricola\" is null");
            return (Criteria) this;
        }

        public Criteria andMatricolaIsNotNull() {
            addCriterion("\"matricola\" is not null");
            return (Criteria) this;
        }

        public Criteria andMatricolaEqualTo(String value) {
            addCriterion("\"matricola\" =", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaNotEqualTo(String value) {
            addCriterion("\"matricola\" <>", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaGreaterThan(String value) {
            addCriterion("\"matricola\" >", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaGreaterThanOrEqualTo(String value) {
            addCriterion("\"matricola\" >=", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaLessThan(String value) {
            addCriterion("\"matricola\" <", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaLessThanOrEqualTo(String value) {
            addCriterion("\"matricola\" <=", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaLike(String value) {
            addCriterion("\"matricola\" like", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaNotLike(String value) {
            addCriterion("\"matricola\" not like", value, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaIn(List<String> values) {
            addCriterion("\"matricola\" in", values, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaNotIn(List<String> values) {
            addCriterion("\"matricola\" not in", values, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaBetween(String value1, String value2) {
            addCriterion("\"matricola\" between", value1, value2, "matricola");
            return (Criteria) this;
        }

        public Criteria andMatricolaNotBetween(String value1, String value2) {
            addCriterion("\"matricola\" not between", value1, value2, "matricola");
            return (Criteria) this;
        }

        public Criteria andSocietaIdIsNull() {
            addCriterion("\"societa_id\" is null");
            return (Criteria) this;
        }

        public Criteria andSocietaIdIsNotNull() {
            addCriterion("\"societa_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andSocietaIdEqualTo(Integer value) {
            addCriterion("\"societa_id\" =", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdNotEqualTo(Integer value) {
            addCriterion("\"societa_id\" <>", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdGreaterThan(Integer value) {
            addCriterion("\"societa_id\" >", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"societa_id\" >=", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdLessThan(Integer value) {
            addCriterion("\"societa_id\" <", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"societa_id\" <=", value, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdIn(List<Integer> values) {
            addCriterion("\"societa_id\" in", values, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdNotIn(List<Integer> values) {
            addCriterion("\"societa_id\" not in", values, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdBetween(Integer value1, Integer value2) {
            addCriterion("\"societa_id\" between", value1, value2, "societaId");
            return (Criteria) this;
        }

        public Criteria andSocietaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"societa_id\" not between", value1, value2, "societaId");
            return (Criteria) this;
        }

        public Criteria andStatoIsNull() {
            addCriterion("\"stato\" is null");
            return (Criteria) this;
        }

        public Criteria andStatoIsNotNull() {
            addCriterion("\"stato\" is not null");
            return (Criteria) this;
        }

        public Criteria andStatoEqualTo(String value) {
            addCriterion("\"stato\" =", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotEqualTo(String value) {
            addCriterion("\"stato\" <>", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoGreaterThan(String value) {
            addCriterion("\"stato\" >", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoGreaterThanOrEqualTo(String value) {
            addCriterion("\"stato\" >=", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLessThan(String value) {
            addCriterion("\"stato\" <", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLessThanOrEqualTo(String value) {
            addCriterion("\"stato\" <=", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoLike(String value) {
            addCriterion("\"stato\" like", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotLike(String value) {
            addCriterion("\"stato\" not like", value, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoIn(List<String> values) {
            addCriterion("\"stato\" in", values, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotIn(List<String> values) {
            addCriterion("\"stato\" not in", values, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoBetween(String value1, String value2) {
            addCriterion("\"stato\" between", value1, value2, "stato");
            return (Criteria) this;
        }

        public Criteria andStatoNotBetween(String value1, String value2) {
            addCriterion("\"stato\" not between", value1, value2, "stato");
            return (Criteria) this;
        }

        public Criteria andCreatoIsNull() {
            addCriterion("\"creato\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatoIsNotNull() {
            addCriterion("\"creato\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoEqualTo(Date value) {
            addCriterion("\"creato\" =", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoNotEqualTo(Date value) {
            addCriterion("\"creato\" <>", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoGreaterThan(Date value) {
            addCriterion("\"creato\" >", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"creato\" >=", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoLessThan(Date value) {
            addCriterion("\"creato\" <", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoLessThanOrEqualTo(Date value) {
            addCriterion("\"creato\" <=", value, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoIn(List<Date> values) {
            addCriterion("\"creato\" in", values, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoNotIn(List<Date> values) {
            addCriterion("\"creato\" not in", values, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoBetween(Date value1, Date value2) {
            addCriterion("\"creato\" between", value1, value2, "creato");
            return (Criteria) this;
        }

        public Criteria andCreatoNotBetween(Date value1, Date value2) {
            addCriterion("\"creato\" not between", value1, value2, "creato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoIsNull() {
            addCriterion("\"aggiornato\" is null");
            return (Criteria) this;
        }

        public Criteria andAggiornatoIsNotNull() {
            addCriterion("\"aggiornato\" is not null");
            return (Criteria) this;
        }

        public Criteria andAggiornatoEqualTo(Date value) {
            addCriterion("\"aggiornato\" =", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoNotEqualTo(Date value) {
            addCriterion("\"aggiornato\" <>", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoGreaterThan(Date value) {
            addCriterion("\"aggiornato\" >", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"aggiornato\" >=", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoLessThan(Date value) {
            addCriterion("\"aggiornato\" <", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoLessThanOrEqualTo(Date value) {
            addCriterion("\"aggiornato\" <=", value, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoIn(List<Date> values) {
            addCriterion("\"aggiornato\" in", values, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoNotIn(List<Date> values) {
            addCriterion("\"aggiornato\" not in", values, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoBetween(Date value1, Date value2) {
            addCriterion("\"aggiornato\" between", value1, value2, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andAggiornatoNotBetween(Date value1, Date value2) {
            addCriterion("\"aggiornato\" not between", value1, value2, "aggiornato");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteIsNull() {
            addCriterion("\"tipo_utente\" is null");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteIsNotNull() {
            addCriterion("\"tipo_utente\" is not null");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteEqualTo(String value) {
            addCriterion("\"tipo_utente\" =", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteNotEqualTo(String value) {
            addCriterion("\"tipo_utente\" <>", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteGreaterThan(String value) {
            addCriterion("\"tipo_utente\" >", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteGreaterThanOrEqualTo(String value) {
            addCriterion("\"tipo_utente\" >=", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteLessThan(String value) {
            addCriterion("\"tipo_utente\" <", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteLessThanOrEqualTo(String value) {
            addCriterion("\"tipo_utente\" <=", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteLike(String value) {
            addCriterion("\"tipo_utente\" like", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteNotLike(String value) {
            addCriterion("\"tipo_utente\" not like", value, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteIn(List<String> values) {
            addCriterion("\"tipo_utente\" in", values, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteNotIn(List<String> values) {
            addCriterion("\"tipo_utente\" not in", values, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteBetween(String value1, String value2) {
            addCriterion("\"tipo_utente\" between", value1, value2, "tipoUtente");
            return (Criteria) this;
        }

        public Criteria andTipoUtenteNotBetween(String value1, String value2) {
            addCriterion("\"tipo_utente\" not between", value1, value2, "tipoUtente");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 23 15:35:12 CET 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.T_UTENTI
     *
     * @mbg.generated Fri Jan 23 15:35:12 CET 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}