package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Accesso;
import srl.neotech.ms_dipendenti.dto.AccessoExample;

public interface AccessoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    long countByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int deleteByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int insert(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int insertSelective(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    List<Accesso> selectByExample(AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    Accesso selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("row") Accesso row, @Param("example") AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("row") Accesso row, @Param("example") AccessoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(Accesso row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_ACCESSI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(Accesso row);
}