package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Configurazione;
import srl.neotech.ms_dipendenti.dto.ConfigurazioneExample;

public interface ConfigurazioneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    long countByExample(ConfigurazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int deleteByExample(ConfigurazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int deleteByPrimaryKey(String chiave);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int insert(Configurazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int insertSelective(Configurazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    List<Configurazione> selectByExample(ConfigurazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    Configurazione selectByPrimaryKey(String chiave);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int updateByExampleSelective(@Param("row") Configurazione row, @Param("example") ConfigurazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int updateByExample(@Param("row") Configurazione row, @Param("example") ConfigurazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int updateByPrimaryKeySelective(Configurazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_CONFIGURAZIONI
     *
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
     */
    int updateByPrimaryKey(Configurazione row);
}