package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Prenotazione;
import srl.neotech.ms_dipendenti.dto.PrenotazioneExample;

public interface PrenotazioneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    long countByExample(PrenotazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int deleteByExample(PrenotazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int insert(Prenotazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int insertSelective(Prenotazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    List<Prenotazione> selectByExample(PrenotazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    Prenotazione selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByExampleSelective(@Param("row") Prenotazione row, @Param("example") PrenotazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByExample(@Param("row") Prenotazione row, @Param("example") PrenotazioneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByPrimaryKeySelective(Prenotazione row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_PRENOTAZIONI
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByPrimaryKey(Prenotazione row);
}