package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Societa;
import srl.neotech.ms_dipendenti.dto.SocietaExample;

public interface SocietaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    long countByExample(SocietaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int deleteByExample(SocietaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int insert(Societa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int insertSelective(Societa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    List<Societa> selectByExample(SocietaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    Societa selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByExampleSelective(@Param("row") Societa row, @Param("example") SocietaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByExample(@Param("row") Societa row, @Param("example") SocietaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByPrimaryKeySelective(Societa row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_SOCIETA
     *
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
     */
    int updateByPrimaryKey(Societa row);
}