package srl.neotech.ms_dipendenti.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import srl.neotech.ms_dipendenti.dto.Utente;
import srl.neotech.ms_dipendenti.dto.UtenteExample;

public interface UtenteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    long countByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int deleteByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int insert(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int insertSelective(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    List<Utente> selectByExample(UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    Utente selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("row") Utente row, @Param("example") UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("row") Utente row, @Param("example") UtenteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(Utente row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.T_UTENTI
     *
<<<<<<< Updated upstream
     * @mbg.generated Mon Mar 02 16:43:28 CET 2026
=======
     * @mbg.generated Tue Feb 17 08:54:50 CET 2026
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(Utente row);
}